version: "3.9"

services:
  server:
      build: tornado/
      ports:
        - "8888:8888"

  react:
    build: frontend/
    ports:
      - "3000:3000"

  django:
    build: backend/
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"