export const REGISTER_LIST_REQUEST = 'REGISTER_LIST_REQUEST'
export const REGISTER_LIST_SUCCESS = 'REGISTER_LIST_SUCCESS'
export const REGISTER_LIST_FAIL = 'REGISTER_LIST_FAIL'

export const REGISTER_DETAILS_REQUEST = 'REGISTER_DETAILS_REQUEST'
export const REGISTER_DETAILS_SUCCESS = 'REGISTER_DETAILS_SUCCESS'
export const REGISTER_DETAILS_FAIL = 'REGISTER_DETAILS_FAIL'

export const REGISTER_DELETE_REQUEST = 'REGISTER_DELETE_REQUEST'
export const REGISTER_DELETE_SUCCESS = 'REGISTER_DELETE_SUCCESS'
export const REGISTER_DELETE_FAIL = 'REGISTER_DELETE_FAIL'

export const REGISTER_CREATE_REQUEST = 'REGISTER_CREATE_REQUEST'
export const REGISTER_CREATE_SUCCESS = 'REGISTER_CREATE_SUCCESS'
export const REGISTER_CREATE_FAIL = 'REGISTER_CREATE_FAIL'
export const REGISTER_CREATE_RESET = 'REGISTER_CREATE_RESET'


export const REGISTER_UPDATE_REQUEST = 'REGISTER_UPDATE_REQUEST'
export const REGISTER_UPDATE_SUCCESS = 'REGISTER_UPDATE_SUCCESS'
export const REGISTER_UPDATE_FAIL = 'REGISTER_UPDATE_FAIL'
export const REGISTER_UPDATE_RESET = 'REGISTER_UPDATE_RESET'
