export const TEST_LIST_REQUEST = 'TEST_LIST_REQUEST'
export const TEST_LIST_SUCCESS = 'TEST_LIST_SUCCESS'
export const TEST_LIST_FAIL = 'TEST_LIST_FAIL'

export const TEST_DETAILS_REQUEST = 'TEST_DETAILS_REQUEST'
export const TEST_DETAILS_SUCCESS = 'TEST_DETAILS_SUCCESS'
export const TEST_DETAILS_FAIL = 'TEST_DETAILS_FAIL'


export const TEST_DELETE_REQUEST = 'TEST_DELETE_REQUEST'
export const TEST_DELETE_SUCCESS = 'TEST_DELETE_SUCCESS'
export const TEST_DELETE_FAIL = 'TEST_DELETE_FAIL'
