# Generated by Django 4.0.4 on 2022-04-20 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_num', models.TextField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField(default=False)),
                ('result_description', models.TextField(blank=True, max_length=400, null=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.register')),
            ],
        ),
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('testResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.testresult')),
                ('testRun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.test')),
            ],
        ),
    ]
