# Generated by Django 4.0.4 on 2022-05-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_testresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmethod',
            name='testRun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_name', to='base.test'),
        ),
    ]
