# Generated by Django 4.0.4 on 2022-05-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_testmethod_testrun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='bill_num',
            new_name='reciept',
        ),
    ]
