# Generated by Django 4.0.4 on 2022-05-14 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_alter_testmethod_testrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStarted',
            fields=[
                ('uuid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
