# Generated by Django 4.0.4 on 2022-05-15 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_teststarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststarted',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
