# Generated by Django 4.0.4 on 2022-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_teststarted_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmethod',
            name='validation',
            field=models.TextField(null=True),
        ),
    ]
