# Generated by Django 4.0.4 on 2022-05-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_testmethod_validation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmethod',
            old_name='validation',
            new_name='validationResult',
        ),
    ]
