# Generated by Django 4.0.4 on 2022-05-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_validation_testmethod_validationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmethod',
            name='validationResult',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
