# Generated by Django 4.0.4 on 2022-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_testmethod_validationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
