# Generated by Django 4.0.4 on 2022-06-05 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_testresult_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('uuid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
